// <auto-generated />
namespace Doctor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Medicine_And_Reportsa_and_prescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Medicine_And_Reportsa_and_prescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201812032203381_Medicine_And_Reportsa_and_prescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
